name: GitHub-Profile-3D-Contrib

on:
  push:
    branches: [main]
  schedule: # 07:00 VN == 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Make changes and push
        run: |
          # Your script or commands that modify the repo
          git add -A
          git commit -m "generated"
          git push origin HEAD:${{ github.ref }}
